# docker-compose.yml

version: '3.7'

services:
  fastapi_app:
    build:
      context: .
      dockerfile: ./docker/fastapi/Dockerfile
    ports:
      - "5555:5555"  # Cambiado el puerto externo de 8000 a 5555
    networks:
      - traefik_public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`0.0.0.0`)"
      - "traefik.http.services.fastapi.loadbalancer.server.port=5555"

  traefik:
    build:
      context: .
      dockerfile: ./docker/traefik/Dockerfile
    ports:
      - "8443:443"  # Cambiado el puerto externo de 80 a 8443
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./docker/traefik/letsencrypt:/letsencrypt"  # Mapeo del directorio para almacenar los certificados
    networks:
      - traefik_public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`0.0.0.0`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.api.service=api@internal"

networks:
  traefik_public:
    external: true
